<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>ThisShard.Database.Core</RootNamespace>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <Version>0.1.0</Version>
        <Title>ThisShard.DataTransfer.Core</Title>
        <Authors>ThisShard</Authors>
        <Description>Core library for transferring data between different sources</Description>
        <Copyright>ThisShard</Copyright>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
      <OutputPath>..\bin\Debug/net8.0/</OutputPath>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
      <OutputPath>..\bin\Release/net8.0/</OutputPath>
    </PropertyGroup>

</Project>
