<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>ThisShard.Database.Infrastructure</RootNamespace>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <Version>0.1.0</Version>
        <Title>ThisShard.DataTransfer.Excel</Title>
        <Authors>ThisShard</Authors>
        <Description>Data transfer for Excel</Description>
        <Copyright>ThisShard</Copyright>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="ExcelDataReader" Version="3.9.0" />
      <PackageReference Include="LargeXlsx" Version="2.0.1" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\ThisShard.DataTransfer.Core\ThisShard.DataTransfer.Core.csproj" />
    </ItemGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
        <OutputPath>..\bin\Debug/net8.0/</OutputPath>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
        <OutputPath>..\bin\Release/net8.0/</OutputPath>
    </PropertyGroup>

</Project>
